using System;
using System.Linq;
using System.Windows.Forms;

namespace ResepsiyonOtomasyon
{
    public partial class WF_giris : Form
    {
        public static string deger;
        public WF_giris()
        {
            InitializeComponent();
        }
        otelResepsiyonDataContext otel = new otelResepsiyonDataContext();
        //otel object
        //classin ismi. Classes auto-generated by the Object Relational Designer (aka LINQ to SQL designer)
        private void btnGiris_Click(object sender, EventArgs e)
            //veritabani isemlerimi contexle getiriyorum                             
            //baglanti ac kapa islemler context uzerinden getiriyorum 
        {
            if (txtKullanici.Text == "" && txt_sifre.Text == "")
            {
                MessageBox.Show("Kullanıcı Adını ve Parolayı Girmediniz.");
            }
            else if (txt_sifre.Text == "")
            {
                MessageBox.Show("Sifreyi Girmediniz.");
            }
            else if (txtKullanici.Text == "")
            {
                MessageBox.Show("Kullanici ad Girmediniz.");
            }
            else
            {
                if (otel.tbl_giris.Any(q => q.Kullanici == txtKullanici.Text && q.sifre == txt_sifre.Text))
                    //
                {
                    WF_progressBar progress = new WF_progressBar();
                    progress.Show();
                    deger = txtKullanici.Text;
                    this.Hide();
                }
                else
                {
                    MessageBox.Show("Yalnis giris!"); txtKullanici.Text = ""; txt_sifre.Text = "";
                }

            }

        }

        private void WF_giris_Load(object sender, EventArgs e)
        {

        }

       
    }
}
