#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResepsiyonOtomasyon
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hotel")]
	public partial class otelResepsiyonDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_musteri(tbl_musteri instance);
    partial void Updatetbl_musteri(tbl_musteri instance);
    partial void Deletetbl_musteri(tbl_musteri instance);
    partial void Inserttbl_ucret(tbl_ucret instance);
    partial void Updatetbl_ucret(tbl_ucret instance);
    partial void Deletetbl_ucret(tbl_ucret instance);
    partial void Inserttbl_giri(tbl_giri instance);
    partial void Updatetbl_giri(tbl_giri instance);
    partial void Deletetbl_giri(tbl_giri instance);
    partial void Inserttbl_Personel(tbl_Personel instance);
    partial void Updatetbl_Personel(tbl_Personel instance);
    partial void Deletetbl_Personel(tbl_Personel instance);
    partial void Inserttbl_rezervasyon(tbl_rezervasyon instance);
    partial void Updatetbl_rezervasyon(tbl_rezervasyon instance);
    partial void Deletetbl_rezervasyon(tbl_rezervasyon instance);
    partial void Inserttbl_gecmi(tbl_gecmi instance);
    partial void Updatetbl_gecmi(tbl_gecmi instance);
    partial void Deletetbl_gecmi(tbl_gecmi instance);
    partial void Inserttbl_odalar(tbl_odalar instance);
    partial void Updatetbl_odalar(tbl_odalar instance);
    partial void Deletetbl_odalar(tbl_odalar instance);
    #endregion
		
		public otelResepsiyonDataContext() : 
				base(global::ResepsiyonOtomasyon.Properties.Settings.Default.hotelConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public otelResepsiyonDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public otelResepsiyonDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public otelResepsiyonDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public otelResepsiyonDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_musteri> tbl_musteris
		{
			get
			{
				return this.GetTable<tbl_musteri>();
			}
		}
		
		public System.Data.Linq.Table<tbl_ucret> tbl_ucrets
		{
			get
			{
				return this.GetTable<tbl_ucret>();
			}
		}
		
		public System.Data.Linq.Table<tbl_giri> tbl_giris
		{
			get
			{
				return this.GetTable<tbl_giri>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Personel> tbl_Personels
		{
			get
			{
				return this.GetTable<tbl_Personel>();
			}
		}
		
		public System.Data.Linq.Table<tbl_rezervasyon> tbl_rezervasyons
		{
			get
			{
				return this.GetTable<tbl_rezervasyon>();
			}
		}
		
		public System.Data.Linq.Table<tbl_gecmi> tbl_gecmis
		{
			get
			{
				return this.GetTable<tbl_gecmi>();
			}
		}
		
		public System.Data.Linq.Table<tbl_odalar> tbl_odalars
		{
			get
			{
				return this.GetTable<tbl_odalar>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_musteri")]
	public partial class tbl_musteri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _AdiSoyadi;
		
		private System.Nullable<int> _CepTel;
		
		private System.Nullable<int> _isTel;
		
		private System.Nullable<int> _EvTel;
		
		private string _mailAdress;
		
		private string _Ulke;
		
		private System.Nullable<System.DateTime> _girisTarih;
		
		private System.Nullable<System.DateTime> _cikisTarih;
		
		private System.Nullable<int> _KisiSayisi;
		
		private string _sehir;
		
		private string _seriNo;
		
		private string _AnaAdi;
		
		private string _BabaAdi;
		
		private string _Dogumyeri;
		
		private System.Nullable<System.DateTime> _DogumTarih;
		
		private string _PasaportNo;
		
		private string _VerildigiUlke;
		
		private System.Nullable<System.DateTime> _VerildigiTarih;
		
		private System.Nullable<System.DateTime> _BitisTarih;
		
		private string _NotBilgi;
		
		private string _Adres;
		
		private string _cinsiyet;
		
		private System.Nullable<int> _odaNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnAdiSoyadiChanging(string value);
    partial void OnAdiSoyadiChanged();
    partial void OnCepTelChanging(System.Nullable<int> value);
    partial void OnCepTelChanged();
    partial void OnisTelChanging(System.Nullable<int> value);
    partial void OnisTelChanged();
    partial void OnEvTelChanging(System.Nullable<int> value);
    partial void OnEvTelChanged();
    partial void OnmailAdressChanging(string value);
    partial void OnmailAdressChanged();
    partial void OnUlkeChanging(string value);
    partial void OnUlkeChanged();
    partial void OngirisTarihChanging(System.Nullable<System.DateTime> value);
    partial void OngirisTarihChanged();
    partial void OncikisTarihChanging(System.Nullable<System.DateTime> value);
    partial void OncikisTarihChanged();
    partial void OnKisiSayisiChanging(System.Nullable<int> value);
    partial void OnKisiSayisiChanged();
    partial void OnsehirChanging(string value);
    partial void OnsehirChanged();
    partial void OnseriNoChanging(string value);
    partial void OnseriNoChanged();
    partial void OnAnaAdiChanging(string value);
    partial void OnAnaAdiChanged();
    partial void OnBabaAdiChanging(string value);
    partial void OnBabaAdiChanged();
    partial void OnDogumyeriChanging(string value);
    partial void OnDogumyeriChanged();
    partial void OnDogumTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnDogumTarihChanged();
    partial void OnPasaportNoChanging(string value);
    partial void OnPasaportNoChanged();
    partial void OnVerildigiUlkeChanging(string value);
    partial void OnVerildigiUlkeChanged();
    partial void OnVerildigiTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnVerildigiTarihChanged();
    partial void OnBitisTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnBitisTarihChanged();
    partial void OnNotBilgiChanging(string value);
    partial void OnNotBilgiChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OncinsiyetChanging(string value);
    partial void OncinsiyetChanged();
    partial void OnodaNoChanging(System.Nullable<int> value);
    partial void OnodaNoChanged();
    #endregion
		
		public tbl_musteri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdiSoyadi", DbType="NChar(50)")]
		public string AdiSoyadi
		{
			get
			{
				return this._AdiSoyadi;
			}
			set
			{
				if ((this._AdiSoyadi != value))
				{
					this.OnAdiSoyadiChanging(value);
					this.SendPropertyChanging();
					this._AdiSoyadi = value;
					this.SendPropertyChanged("AdiSoyadi");
					this.OnAdiSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CepTel", DbType="Int")]
		public System.Nullable<int> CepTel
		{
			get
			{
				return this._CepTel;
			}
			set
			{
				if ((this._CepTel != value))
				{
					this.OnCepTelChanging(value);
					this.SendPropertyChanging();
					this._CepTel = value;
					this.SendPropertyChanged("CepTel");
					this.OnCepTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isTel", DbType="Int")]
		public System.Nullable<int> isTel
		{
			get
			{
				return this._isTel;
			}
			set
			{
				if ((this._isTel != value))
				{
					this.OnisTelChanging(value);
					this.SendPropertyChanging();
					this._isTel = value;
					this.SendPropertyChanged("isTel");
					this.OnisTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvTel", DbType="Int")]
		public System.Nullable<int> EvTel
		{
			get
			{
				return this._EvTel;
			}
			set
			{
				if ((this._EvTel != value))
				{
					this.OnEvTelChanging(value);
					this.SendPropertyChanging();
					this._EvTel = value;
					this.SendPropertyChanged("EvTel");
					this.OnEvTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mailAdress", DbType="NChar(30)")]
		public string mailAdress
		{
			get
			{
				return this._mailAdress;
			}
			set
			{
				if ((this._mailAdress != value))
				{
					this.OnmailAdressChanging(value);
					this.SendPropertyChanging();
					this._mailAdress = value;
					this.SendPropertyChanged("mailAdress");
					this.OnmailAdressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulke", DbType="NChar(20)")]
		public string Ulke
		{
			get
			{
				return this._Ulke;
			}
			set
			{
				if ((this._Ulke != value))
				{
					this.OnUlkeChanging(value);
					this.SendPropertyChanging();
					this._Ulke = value;
					this.SendPropertyChanged("Ulke");
					this.OnUlkeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_girisTarih", DbType="Date")]
		public System.Nullable<System.DateTime> girisTarih
		{
			get
			{
				return this._girisTarih;
			}
			set
			{
				if ((this._girisTarih != value))
				{
					this.OngirisTarihChanging(value);
					this.SendPropertyChanging();
					this._girisTarih = value;
					this.SendPropertyChanged("girisTarih");
					this.OngirisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cikisTarih", DbType="Date")]
		public System.Nullable<System.DateTime> cikisTarih
		{
			get
			{
				return this._cikisTarih;
			}
			set
			{
				if ((this._cikisTarih != value))
				{
					this.OncikisTarihChanging(value);
					this.SendPropertyChanging();
					this._cikisTarih = value;
					this.SendPropertyChanged("cikisTarih");
					this.OncikisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KisiSayisi", DbType="Int")]
		public System.Nullable<int> KisiSayisi
		{
			get
			{
				return this._KisiSayisi;
			}
			set
			{
				if ((this._KisiSayisi != value))
				{
					this.OnKisiSayisiChanging(value);
					this.SendPropertyChanging();
					this._KisiSayisi = value;
					this.SendPropertyChanged("KisiSayisi");
					this.OnKisiSayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sehir", DbType="NChar(20)")]
		public string sehir
		{
			get
			{
				return this._sehir;
			}
			set
			{
				if ((this._sehir != value))
				{
					this.OnsehirChanging(value);
					this.SendPropertyChanging();
					this._sehir = value;
					this.SendPropertyChanged("sehir");
					this.OnsehirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seriNo", DbType="NChar(20)")]
		public string seriNo
		{
			get
			{
				return this._seriNo;
			}
			set
			{
				if ((this._seriNo != value))
				{
					this.OnseriNoChanging(value);
					this.SendPropertyChanging();
					this._seriNo = value;
					this.SendPropertyChanged("seriNo");
					this.OnseriNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnaAdi", DbType="NChar(20)")]
		public string AnaAdi
		{
			get
			{
				return this._AnaAdi;
			}
			set
			{
				if ((this._AnaAdi != value))
				{
					this.OnAnaAdiChanging(value);
					this.SendPropertyChanging();
					this._AnaAdi = value;
					this.SendPropertyChanged("AnaAdi");
					this.OnAnaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BabaAdi", DbType="NChar(20)")]
		public string BabaAdi
		{
			get
			{
				return this._BabaAdi;
			}
			set
			{
				if ((this._BabaAdi != value))
				{
					this.OnBabaAdiChanging(value);
					this.SendPropertyChanging();
					this._BabaAdi = value;
					this.SendPropertyChanged("BabaAdi");
					this.OnBabaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dogumyeri", DbType="NChar(20)")]
		public string Dogumyeri
		{
			get
			{
				return this._Dogumyeri;
			}
			set
			{
				if ((this._Dogumyeri != value))
				{
					this.OnDogumyeriChanging(value);
					this.SendPropertyChanging();
					this._Dogumyeri = value;
					this.SendPropertyChanged("Dogumyeri");
					this.OnDogumyeriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DogumTarih", DbType="Date")]
		public System.Nullable<System.DateTime> DogumTarih
		{
			get
			{
				return this._DogumTarih;
			}
			set
			{
				if ((this._DogumTarih != value))
				{
					this.OnDogumTarihChanging(value);
					this.SendPropertyChanging();
					this._DogumTarih = value;
					this.SendPropertyChanged("DogumTarih");
					this.OnDogumTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasaportNo", DbType="NChar(20)")]
		public string PasaportNo
		{
			get
			{
				return this._PasaportNo;
			}
			set
			{
				if ((this._PasaportNo != value))
				{
					this.OnPasaportNoChanging(value);
					this.SendPropertyChanging();
					this._PasaportNo = value;
					this.SendPropertyChanged("PasaportNo");
					this.OnPasaportNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerildigiUlke", DbType="NChar(20)")]
		public string VerildigiUlke
		{
			get
			{
				return this._VerildigiUlke;
			}
			set
			{
				if ((this._VerildigiUlke != value))
				{
					this.OnVerildigiUlkeChanging(value);
					this.SendPropertyChanging();
					this._VerildigiUlke = value;
					this.SendPropertyChanged("VerildigiUlke");
					this.OnVerildigiUlkeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerildigiTarih", DbType="Date")]
		public System.Nullable<System.DateTime> VerildigiTarih
		{
			get
			{
				return this._VerildigiTarih;
			}
			set
			{
				if ((this._VerildigiTarih != value))
				{
					this.OnVerildigiTarihChanging(value);
					this.SendPropertyChanging();
					this._VerildigiTarih = value;
					this.SendPropertyChanged("VerildigiTarih");
					this.OnVerildigiTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BitisTarih", DbType="Date")]
		public System.Nullable<System.DateTime> BitisTarih
		{
			get
			{
				return this._BitisTarih;
			}
			set
			{
				if ((this._BitisTarih != value))
				{
					this.OnBitisTarihChanging(value);
					this.SendPropertyChanging();
					this._BitisTarih = value;
					this.SendPropertyChanged("BitisTarih");
					this.OnBitisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotBilgi", DbType="NChar(100)")]
		public string NotBilgi
		{
			get
			{
				return this._NotBilgi;
			}
			set
			{
				if ((this._NotBilgi != value))
				{
					this.OnNotBilgiChanging(value);
					this.SendPropertyChanging();
					this._NotBilgi = value;
					this.SendPropertyChanged("NotBilgi");
					this.OnNotBilgiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NChar(50)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cinsiyet", DbType="NChar(10)")]
		public string cinsiyet
		{
			get
			{
				return this._cinsiyet;
			}
			set
			{
				if ((this._cinsiyet != value))
				{
					this.OncinsiyetChanging(value);
					this.SendPropertyChanging();
					this._cinsiyet = value;
					this.SendPropertyChanged("cinsiyet");
					this.OncinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odaNo", DbType="Int")]
		public System.Nullable<int> odaNo
		{
			get
			{
				return this._odaNo;
			}
			set
			{
				if ((this._odaNo != value))
				{
					this.OnodaNoChanging(value);
					this.SendPropertyChanging();
					this._odaNo = value;
					this.SendPropertyChanged("odaNo");
					this.OnodaNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ucret")]
	public partial class tbl_ucret : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<decimal> _ucret;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnucretChanging(System.Nullable<decimal> value);
    partial void OnucretChanged();
    #endregion
		
		public tbl_ucret()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ucret", DbType="Money")]
		public System.Nullable<decimal> ucret
		{
			get
			{
				return this._ucret;
			}
			set
			{
				if ((this._ucret != value))
				{
					this.OnucretChanging(value);
					this.SendPropertyChanging();
					this._ucret = value;
					this.SendPropertyChanged("ucret");
					this.OnucretChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_giris")]
	public partial class tbl_giri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Kullanici;
		
		private string _sifre;
		
		private string _AdSoyad;
		
		private System.Nullable<int> _TcNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnKullaniciChanging(string value);
    partial void OnKullaniciChanged();
    partial void OnsifreChanging(string value);
    partial void OnsifreChanged();
    partial void OnAdSoyadChanging(string value);
    partial void OnAdSoyadChanged();
    partial void OnTcNoChanging(System.Nullable<int> value);
    partial void OnTcNoChanged();
    #endregion
		
		public tbl_giri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kullanici", DbType="NChar(20)")]
		public string Kullanici
		{
			get
			{
				return this._Kullanici;
			}
			set
			{
				if ((this._Kullanici != value))
				{
					this.OnKullaniciChanging(value);
					this.SendPropertyChanging();
					this._Kullanici = value;
					this.SendPropertyChanged("Kullanici");
					this.OnKullaniciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="NVarChar(20)")]
		public string sifre
		{
			get
			{
				return this._sifre;
			}
			set
			{
				if ((this._sifre != value))
				{
					this.OnsifreChanging(value);
					this.SendPropertyChanging();
					this._sifre = value;
					this.SendPropertyChanged("sifre");
					this.OnsifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdSoyad", DbType="NChar(30)")]
		public string AdSoyad
		{
			get
			{
				return this._AdSoyad;
			}
			set
			{
				if ((this._AdSoyad != value))
				{
					this.OnAdSoyadChanging(value);
					this.SendPropertyChanging();
					this._AdSoyad = value;
					this.SendPropertyChanged("AdSoyad");
					this.OnAdSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TcNo", DbType="Int")]
		public System.Nullable<int> TcNo
		{
			get
			{
				return this._TcNo;
			}
			set
			{
				if ((this._TcNo != value))
				{
					this.OnTcNoChanging(value);
					this.SendPropertyChanging();
					this._TcNo = value;
					this.SendPropertyChanged("TcNo");
					this.OnTcNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Personel")]
	public partial class tbl_Personel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _TCno;
		
		private string _Adi;
		
		private string _Soyadi;
		
		private string _Cinsiyet;
		
		private System.Nullable<int> _TelNo;
		
		private string _MedeniHali;
		
		private System.Nullable<decimal> _Maas;
		
		private System.Nullable<System.DateTime> _dogumTarih;
		
		private string _adress;
		
		private System.Nullable<System.DateTime> _girisTarih;
		
		private string _gorevi;
		
		private System.Nullable<int> _mesaiSaati;
		
		private System.Nullable<decimal> _mesaiUcreti;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnTCnoChanging(System.Nullable<int> value);
    partial void OnTCnoChanged();
    partial void OnAdiChanging(string value);
    partial void OnAdiChanged();
    partial void OnSoyadiChanging(string value);
    partial void OnSoyadiChanged();
    partial void OnCinsiyetChanging(string value);
    partial void OnCinsiyetChanged();
    partial void OnTelNoChanging(System.Nullable<int> value);
    partial void OnTelNoChanged();
    partial void OnMedeniHaliChanging(string value);
    partial void OnMedeniHaliChanged();
    partial void OnMaasChanging(System.Nullable<decimal> value);
    partial void OnMaasChanged();
    partial void OndogumTarihChanging(System.Nullable<System.DateTime> value);
    partial void OndogumTarihChanged();
    partial void OnadressChanging(string value);
    partial void OnadressChanged();
    partial void OngirisTarihChanging(System.Nullable<System.DateTime> value);
    partial void OngirisTarihChanged();
    partial void OngoreviChanging(string value);
    partial void OngoreviChanged();
    partial void OnmesaiSaatiChanging(System.Nullable<int> value);
    partial void OnmesaiSaatiChanged();
    partial void OnmesaiUcretiChanging(System.Nullable<decimal> value);
    partial void OnmesaiUcretiChanged();
    #endregion
		
		public tbl_Personel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCno", DbType="Int")]
		public System.Nullable<int> TCno
		{
			get
			{
				return this._TCno;
			}
			set
			{
				if ((this._TCno != value))
				{
					this.OnTCnoChanging(value);
					this.SendPropertyChanging();
					this._TCno = value;
					this.SendPropertyChanged("TCno");
					this.OnTCnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NChar(20)")]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this.OnAdiChanging(value);
					this.SendPropertyChanging();
					this._Adi = value;
					this.SendPropertyChanged("Adi");
					this.OnAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyadi", DbType="NChar(20)")]
		public string Soyadi
		{
			get
			{
				return this._Soyadi;
			}
			set
			{
				if ((this._Soyadi != value))
				{
					this.OnSoyadiChanging(value);
					this.SendPropertyChanging();
					this._Soyadi = value;
					this.SendPropertyChanged("Soyadi");
					this.OnSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cinsiyet", DbType="NChar(10)")]
		public string Cinsiyet
		{
			get
			{
				return this._Cinsiyet;
			}
			set
			{
				if ((this._Cinsiyet != value))
				{
					this.OnCinsiyetChanging(value);
					this.SendPropertyChanging();
					this._Cinsiyet = value;
					this.SendPropertyChanged("Cinsiyet");
					this.OnCinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelNo", DbType="Int")]
		public System.Nullable<int> TelNo
		{
			get
			{
				return this._TelNo;
			}
			set
			{
				if ((this._TelNo != value))
				{
					this.OnTelNoChanging(value);
					this.SendPropertyChanging();
					this._TelNo = value;
					this.SendPropertyChanged("TelNo");
					this.OnTelNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedeniHali", DbType="NChar(10)")]
		public string MedeniHali
		{
			get
			{
				return this._MedeniHali;
			}
			set
			{
				if ((this._MedeniHali != value))
				{
					this.OnMedeniHaliChanging(value);
					this.SendPropertyChanging();
					this._MedeniHali = value;
					this.SendPropertyChanged("MedeniHali");
					this.OnMedeniHaliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maas", DbType="Money")]
		public System.Nullable<decimal> Maas
		{
			get
			{
				return this._Maas;
			}
			set
			{
				if ((this._Maas != value))
				{
					this.OnMaasChanging(value);
					this.SendPropertyChanging();
					this._Maas = value;
					this.SendPropertyChanged("Maas");
					this.OnMaasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dogumTarih", DbType="Date")]
		public System.Nullable<System.DateTime> dogumTarih
		{
			get
			{
				return this._dogumTarih;
			}
			set
			{
				if ((this._dogumTarih != value))
				{
					this.OndogumTarihChanging(value);
					this.SendPropertyChanging();
					this._dogumTarih = value;
					this.SendPropertyChanged("dogumTarih");
					this.OndogumTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adress", DbType="NVarChar(MAX)")]
		public string adress
		{
			get
			{
				return this._adress;
			}
			set
			{
				if ((this._adress != value))
				{
					this.OnadressChanging(value);
					this.SendPropertyChanging();
					this._adress = value;
					this.SendPropertyChanged("adress");
					this.OnadressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_girisTarih", DbType="Date")]
		public System.Nullable<System.DateTime> girisTarih
		{
			get
			{
				return this._girisTarih;
			}
			set
			{
				if ((this._girisTarih != value))
				{
					this.OngirisTarihChanging(value);
					this.SendPropertyChanging();
					this._girisTarih = value;
					this.SendPropertyChanged("girisTarih");
					this.OngirisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gorevi", DbType="NChar(30)")]
		public string gorevi
		{
			get
			{
				return this._gorevi;
			}
			set
			{
				if ((this._gorevi != value))
				{
					this.OngoreviChanging(value);
					this.SendPropertyChanging();
					this._gorevi = value;
					this.SendPropertyChanged("gorevi");
					this.OngoreviChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mesaiSaati", DbType="Int")]
		public System.Nullable<int> mesaiSaati
		{
			get
			{
				return this._mesaiSaati;
			}
			set
			{
				if ((this._mesaiSaati != value))
				{
					this.OnmesaiSaatiChanging(value);
					this.SendPropertyChanging();
					this._mesaiSaati = value;
					this.SendPropertyChanged("mesaiSaati");
					this.OnmesaiSaatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mesaiUcreti", DbType="Money")]
		public System.Nullable<decimal> mesaiUcreti
		{
			get
			{
				return this._mesaiUcreti;
			}
			set
			{
				if ((this._mesaiUcreti != value))
				{
					this.OnmesaiUcretiChanging(value);
					this.SendPropertyChanging();
					this._mesaiUcreti = value;
					this.SendPropertyChanged("mesaiUcreti");
					this.OnmesaiUcretiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_rezervasyon")]
	public partial class tbl_rezervasyon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _KimlikSeriNo;
		
		private System.Nullable<int> _OdaNo;
		
		private string _AdSoyad;
		
		private System.Nullable<System.DateTime> _Giristarih;
		
		private System.Nullable<int> _Telefon;
		
		private string _Aciklama;
		
		private System.Nullable<System.DateTime> _Cikistarih;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnKimlikSeriNoChanging(System.Nullable<int> value);
    partial void OnKimlikSeriNoChanged();
    partial void OnOdaNoChanging(System.Nullable<int> value);
    partial void OnOdaNoChanged();
    partial void OnAdSoyadChanging(string value);
    partial void OnAdSoyadChanged();
    partial void OnGiristarihChanging(System.Nullable<System.DateTime> value);
    partial void OnGiristarihChanged();
    partial void OnTelefonChanging(System.Nullable<int> value);
    partial void OnTelefonChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnCikistarihChanging(System.Nullable<System.DateTime> value);
    partial void OnCikistarihChanged();
    #endregion
		
		public tbl_rezervasyon()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KimlikSeriNo", DbType="Int")]
		public System.Nullable<int> KimlikSeriNo
		{
			get
			{
				return this._KimlikSeriNo;
			}
			set
			{
				if ((this._KimlikSeriNo != value))
				{
					this.OnKimlikSeriNoChanging(value);
					this.SendPropertyChanging();
					this._KimlikSeriNo = value;
					this.SendPropertyChanged("KimlikSeriNo");
					this.OnKimlikSeriNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdaNo", DbType="Int")]
		public System.Nullable<int> OdaNo
		{
			get
			{
				return this._OdaNo;
			}
			set
			{
				if ((this._OdaNo != value))
				{
					this.OnOdaNoChanging(value);
					this.SendPropertyChanging();
					this._OdaNo = value;
					this.SendPropertyChanged("OdaNo");
					this.OnOdaNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdSoyad", DbType="NChar(30)")]
		public string AdSoyad
		{
			get
			{
				return this._AdSoyad;
			}
			set
			{
				if ((this._AdSoyad != value))
				{
					this.OnAdSoyadChanging(value);
					this.SendPropertyChanging();
					this._AdSoyad = value;
					this.SendPropertyChanged("AdSoyad");
					this.OnAdSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giristarih", DbType="Date")]
		public System.Nullable<System.DateTime> Giristarih
		{
			get
			{
				return this._Giristarih;
			}
			set
			{
				if ((this._Giristarih != value))
				{
					this.OnGiristarihChanging(value);
					this.SendPropertyChanging();
					this._Giristarih = value;
					this.SendPropertyChanged("Giristarih");
					this.OnGiristarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="Int")]
		public System.Nullable<int> Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cikistarih", DbType="Date")]
		public System.Nullable<System.DateTime> Cikistarih
		{
			get
			{
				return this._Cikistarih;
			}
			set
			{
				if ((this._Cikistarih != value))
				{
					this.OnCikistarihChanging(value);
					this.SendPropertyChanging();
					this._Cikistarih = value;
					this.SendPropertyChanged("Cikistarih");
					this.OnCikistarihChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_gecmis")]
	public partial class tbl_gecmi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _AdiSoyadi;
		
		private System.Nullable<int> _CepTel;
		
		private System.Nullable<int> _isTel;
		
		private System.Nullable<int> _EvTel;
		
		private string _mailAdress;
		
		private string _Ulke;
		
		private System.Nullable<System.DateTime> _girisTarih;
		
		private System.Nullable<System.DateTime> _cikisTarih;
		
		private System.Nullable<int> _KisiSayisi;
		
		private string _sehir;
		
		private string _seriNo;
		
		private string _AnaAdi;
		
		private string _BabaAdi;
		
		private string _Dogumyeri;
		
		private System.Nullable<System.DateTime> _DogumTarih;
		
		private string _PasaportNo;
		
		private string _VerildigiUlke;
		
		private System.Nullable<System.DateTime> _VerildigiTarih;
		
		private System.Nullable<System.DateTime> _BitisTarih;
		
		private string _NotBilgi;
		
		private string _Adres;
		
		private string _cinsiyet;
		
		private System.Nullable<int> _odaNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnAdiSoyadiChanging(string value);
    partial void OnAdiSoyadiChanged();
    partial void OnCepTelChanging(System.Nullable<int> value);
    partial void OnCepTelChanged();
    partial void OnisTelChanging(System.Nullable<int> value);
    partial void OnisTelChanged();
    partial void OnEvTelChanging(System.Nullable<int> value);
    partial void OnEvTelChanged();
    partial void OnmailAdressChanging(string value);
    partial void OnmailAdressChanged();
    partial void OnUlkeChanging(string value);
    partial void OnUlkeChanged();
    partial void OngirisTarihChanging(System.Nullable<System.DateTime> value);
    partial void OngirisTarihChanged();
    partial void OncikisTarihChanging(System.Nullable<System.DateTime> value);
    partial void OncikisTarihChanged();
    partial void OnKisiSayisiChanging(System.Nullable<int> value);
    partial void OnKisiSayisiChanged();
    partial void OnsehirChanging(string value);
    partial void OnsehirChanged();
    partial void OnseriNoChanging(string value);
    partial void OnseriNoChanged();
    partial void OnAnaAdiChanging(string value);
    partial void OnAnaAdiChanged();
    partial void OnBabaAdiChanging(string value);
    partial void OnBabaAdiChanged();
    partial void OnDogumyeriChanging(string value);
    partial void OnDogumyeriChanged();
    partial void OnDogumTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnDogumTarihChanged();
    partial void OnPasaportNoChanging(string value);
    partial void OnPasaportNoChanged();
    partial void OnVerildigiUlkeChanging(string value);
    partial void OnVerildigiUlkeChanged();
    partial void OnVerildigiTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnVerildigiTarihChanged();
    partial void OnBitisTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnBitisTarihChanged();
    partial void OnNotBilgiChanging(string value);
    partial void OnNotBilgiChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OncinsiyetChanging(string value);
    partial void OncinsiyetChanged();
    partial void OnodaNoChanging(System.Nullable<int> value);
    partial void OnodaNoChanged();
    #endregion
		
		public tbl_gecmi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdiSoyadi", DbType="NChar(50)")]
		public string AdiSoyadi
		{
			get
			{
				return this._AdiSoyadi;
			}
			set
			{
				if ((this._AdiSoyadi != value))
				{
					this.OnAdiSoyadiChanging(value);
					this.SendPropertyChanging();
					this._AdiSoyadi = value;
					this.SendPropertyChanged("AdiSoyadi");
					this.OnAdiSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CepTel", DbType="Int")]
		public System.Nullable<int> CepTel
		{
			get
			{
				return this._CepTel;
			}
			set
			{
				if ((this._CepTel != value))
				{
					this.OnCepTelChanging(value);
					this.SendPropertyChanging();
					this._CepTel = value;
					this.SendPropertyChanged("CepTel");
					this.OnCepTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isTel", DbType="Int")]
		public System.Nullable<int> isTel
		{
			get
			{
				return this._isTel;
			}
			set
			{
				if ((this._isTel != value))
				{
					this.OnisTelChanging(value);
					this.SendPropertyChanging();
					this._isTel = value;
					this.SendPropertyChanged("isTel");
					this.OnisTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvTel", DbType="Int")]
		public System.Nullable<int> EvTel
		{
			get
			{
				return this._EvTel;
			}
			set
			{
				if ((this._EvTel != value))
				{
					this.OnEvTelChanging(value);
					this.SendPropertyChanging();
					this._EvTel = value;
					this.SendPropertyChanged("EvTel");
					this.OnEvTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mailAdress", DbType="NChar(30)")]
		public string mailAdress
		{
			get
			{
				return this._mailAdress;
			}
			set
			{
				if ((this._mailAdress != value))
				{
					this.OnmailAdressChanging(value);
					this.SendPropertyChanging();
					this._mailAdress = value;
					this.SendPropertyChanged("mailAdress");
					this.OnmailAdressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulke", DbType="NChar(20)")]
		public string Ulke
		{
			get
			{
				return this._Ulke;
			}
			set
			{
				if ((this._Ulke != value))
				{
					this.OnUlkeChanging(value);
					this.SendPropertyChanging();
					this._Ulke = value;
					this.SendPropertyChanged("Ulke");
					this.OnUlkeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_girisTarih", DbType="Date")]
		public System.Nullable<System.DateTime> girisTarih
		{
			get
			{
				return this._girisTarih;
			}
			set
			{
				if ((this._girisTarih != value))
				{
					this.OngirisTarihChanging(value);
					this.SendPropertyChanging();
					this._girisTarih = value;
					this.SendPropertyChanged("girisTarih");
					this.OngirisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cikisTarih", DbType="Date")]
		public System.Nullable<System.DateTime> cikisTarih
		{
			get
			{
				return this._cikisTarih;
			}
			set
			{
				if ((this._cikisTarih != value))
				{
					this.OncikisTarihChanging(value);
					this.SendPropertyChanging();
					this._cikisTarih = value;
					this.SendPropertyChanged("cikisTarih");
					this.OncikisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KisiSayisi", DbType="Int")]
		public System.Nullable<int> KisiSayisi
		{
			get
			{
				return this._KisiSayisi;
			}
			set
			{
				if ((this._KisiSayisi != value))
				{
					this.OnKisiSayisiChanging(value);
					this.SendPropertyChanging();
					this._KisiSayisi = value;
					this.SendPropertyChanged("KisiSayisi");
					this.OnKisiSayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sehir", DbType="NChar(20)")]
		public string sehir
		{
			get
			{
				return this._sehir;
			}
			set
			{
				if ((this._sehir != value))
				{
					this.OnsehirChanging(value);
					this.SendPropertyChanging();
					this._sehir = value;
					this.SendPropertyChanged("sehir");
					this.OnsehirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seriNo", DbType="NChar(20)")]
		public string seriNo
		{
			get
			{
				return this._seriNo;
			}
			set
			{
				if ((this._seriNo != value))
				{
					this.OnseriNoChanging(value);
					this.SendPropertyChanging();
					this._seriNo = value;
					this.SendPropertyChanged("seriNo");
					this.OnseriNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnaAdi", DbType="NChar(20)")]
		public string AnaAdi
		{
			get
			{
				return this._AnaAdi;
			}
			set
			{
				if ((this._AnaAdi != value))
				{
					this.OnAnaAdiChanging(value);
					this.SendPropertyChanging();
					this._AnaAdi = value;
					this.SendPropertyChanged("AnaAdi");
					this.OnAnaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BabaAdi", DbType="NChar(20)")]
		public string BabaAdi
		{
			get
			{
				return this._BabaAdi;
			}
			set
			{
				if ((this._BabaAdi != value))
				{
					this.OnBabaAdiChanging(value);
					this.SendPropertyChanging();
					this._BabaAdi = value;
					this.SendPropertyChanged("BabaAdi");
					this.OnBabaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dogumyeri", DbType="NChar(20)")]
		public string Dogumyeri
		{
			get
			{
				return this._Dogumyeri;
			}
			set
			{
				if ((this._Dogumyeri != value))
				{
					this.OnDogumyeriChanging(value);
					this.SendPropertyChanging();
					this._Dogumyeri = value;
					this.SendPropertyChanged("Dogumyeri");
					this.OnDogumyeriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DogumTarih", DbType="Date")]
		public System.Nullable<System.DateTime> DogumTarih
		{
			get
			{
				return this._DogumTarih;
			}
			set
			{
				if ((this._DogumTarih != value))
				{
					this.OnDogumTarihChanging(value);
					this.SendPropertyChanging();
					this._DogumTarih = value;
					this.SendPropertyChanged("DogumTarih");
					this.OnDogumTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasaportNo", DbType="NChar(20)")]
		public string PasaportNo
		{
			get
			{
				return this._PasaportNo;
			}
			set
			{
				if ((this._PasaportNo != value))
				{
					this.OnPasaportNoChanging(value);
					this.SendPropertyChanging();
					this._PasaportNo = value;
					this.SendPropertyChanged("PasaportNo");
					this.OnPasaportNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerildigiUlke", DbType="NChar(20)")]
		public string VerildigiUlke
		{
			get
			{
				return this._VerildigiUlke;
			}
			set
			{
				if ((this._VerildigiUlke != value))
				{
					this.OnVerildigiUlkeChanging(value);
					this.SendPropertyChanging();
					this._VerildigiUlke = value;
					this.SendPropertyChanged("VerildigiUlke");
					this.OnVerildigiUlkeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerildigiTarih", DbType="Date")]
		public System.Nullable<System.DateTime> VerildigiTarih
		{
			get
			{
				return this._VerildigiTarih;
			}
			set
			{
				if ((this._VerildigiTarih != value))
				{
					this.OnVerildigiTarihChanging(value);
					this.SendPropertyChanging();
					this._VerildigiTarih = value;
					this.SendPropertyChanged("VerildigiTarih");
					this.OnVerildigiTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BitisTarih", DbType="Date")]
		public System.Nullable<System.DateTime> BitisTarih
		{
			get
			{
				return this._BitisTarih;
			}
			set
			{
				if ((this._BitisTarih != value))
				{
					this.OnBitisTarihChanging(value);
					this.SendPropertyChanging();
					this._BitisTarih = value;
					this.SendPropertyChanged("BitisTarih");
					this.OnBitisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotBilgi", DbType="NChar(100)")]
		public string NotBilgi
		{
			get
			{
				return this._NotBilgi;
			}
			set
			{
				if ((this._NotBilgi != value))
				{
					this.OnNotBilgiChanging(value);
					this.SendPropertyChanging();
					this._NotBilgi = value;
					this.SendPropertyChanged("NotBilgi");
					this.OnNotBilgiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NChar(50)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cinsiyet", DbType="NChar(10)")]
		public string cinsiyet
		{
			get
			{
				return this._cinsiyet;
			}
			set
			{
				if ((this._cinsiyet != value))
				{
					this.OncinsiyetChanging(value);
					this.SendPropertyChanging();
					this._cinsiyet = value;
					this.SendPropertyChanged("cinsiyet");
					this.OncinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odaNo", DbType="Int")]
		public System.Nullable<int> odaNo
		{
			get
			{
				return this._odaNo;
			}
			set
			{
				if ((this._odaNo != value))
				{
					this.OnodaNoChanging(value);
					this.SendPropertyChanging();
					this._odaNo = value;
					this.SendPropertyChanged("odaNo");
					this.OnodaNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_odalar")]
	public partial class tbl_odalar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _odaNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnodaNoChanging(System.Nullable<int> value);
    partial void OnodaNoChanged();
    #endregion
		
		public tbl_odalar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odaNo", DbType="Int")]
		public System.Nullable<int> odaNo
		{
			get
			{
				return this._odaNo;
			}
			set
			{
				if ((this._odaNo != value))
				{
					this.OnodaNoChanging(value);
					this.SendPropertyChanging();
					this._odaNo = value;
					this.SendPropertyChanged("odaNo");
					this.OnodaNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
